from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

ay_skidl = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'Conn_02x08_Odd_Even', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_02x08_Odd_Even'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_IDC:IDC-Header_2x08_P2.54mm_Vertical', 'keywords':'connector', 'description':'Generic connector, double row, 02x08, odd/even pin numbering scheme (row 1 odd numbers, row 2 even numbers), script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'~', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='Pin_3',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='Pin_5',func=pin_types.PASSIVE,unit=1),
            Pin(num='7',name='Pin_7',func=pin_types.PASSIVE,unit=1),
            Pin(num='9',name='Pin_9',func=pin_types.PASSIVE,unit=1),
            Pin(num='11',name='Pin_11',func=pin_types.PASSIVE,unit=1),
            Pin(num='13',name='Pin_13',func=pin_types.PASSIVE,unit=1),
            Pin(num='15',name='Pin_15',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='Pin_4',func=pin_types.PASSIVE,unit=1),
            Pin(num='6',name='Pin_6',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='Pin_8',func=pin_types.PASSIVE,unit=1),
            Pin(num='10',name='Pin_10',func=pin_types.PASSIVE,unit=1),
            Pin(num='12',name='Pin_12',func=pin_types.PASSIVE,unit=1),
            Pin(num='14',name='Pin_14',func=pin_types.PASSIVE,unit=1),
            Pin(num='16',name='Pin_16',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'D', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'D'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'Diode_THT:D_DO-41_SOD81_P10.16mm_Horizontal', 'keywords':'diode', 'description':'Diode', 'datasheet':'~', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'LM7805_TO220', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LM7805_TO220'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_THT:TO-220-3_Vertical'], 'footprint':'Package_TO_SOT_THT:TO-220-3_Vertical', 'keywords':'Voltage Regulator 1A Positive', 'description':'Positive 1A 35V Linear Regulator, Fixed Output 5V, TO-220', 'datasheet':'https://www.onsemi.cn/PowerSolutions/document/MC7800-D.PDF', 'pins':[
            Pin(num='1',name='VI',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='VO',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C_Polarized', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C_Polarized'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_THT:CP_Radial_D6.3mm_P2.50mm', 'keywords':'cap capacitor', 'description':'Polarized capacitor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'Capacitor_THT:C_Disc_D5.0mm_W2.5mm_P5.00mm', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'DIN-5', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'DIN-5'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_DIN:DIN5_262degree_Vertical', 'keywords':'circular DIN connector', 'description':'5-pin DIN connector', 'datasheet':'http://www.mouser.com/ds/2/18/40_c091_abd_e-75918.pdf', 'pins':[
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='5',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'Resistor_THT:R_Axial_DIN0207_L6.3mm_D2.5mm_P10.16mm_Horizontal', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'~', 'pins':[
            Pin(num='1',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'6N137', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'6N137'}), 'ref_prefix':'U', 'fplist':['Package_DIP:DIP-8_W7.62mm', 'Package_DIP:DIP-8_W7.62mm'], 'footprint':'Package_DIP:DIP-8_W7.62mm', 'keywords':'High speed optically coupled gates enable', 'description':'Single High Speed LSTTL/TTL Compatible Optocoupler with enable, dV/dt 1000/us, VCM 10, max 7V VCC, DIP-8', 'datasheet':'https://docs.broadcom.com/docs/AV02-0940EN', 'pins':[
            Pin(num='1',name='NC',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1),
            Pin(num='3',name='C',func=pin_types.PASSIVE,unit=1),
            Pin(num='4',name='NC',func=pin_types.PASSIVE,unit=1),
            Pin(num='8',name='VCC',func=pin_types.PWRIN,unit=1),
            Pin(num='5',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='7',name='EN',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='VO',func=pin_types.OPENCOLL,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'AY-3-8910', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AY-3-8910'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Package_DIP:DIP-40_W15.24mm', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='GND',func=pin_types.PWRIN),
            Pin(num='2',name='NC',func=pin_types.NOCONNECT),
            Pin(num='3',name='AoutB',func=pin_types.OUTPUT),
            Pin(num='4',name='AoutA',func=pin_types.OUTPUT),
            Pin(num='5',name='IOB7',func=pin_types.BIDIR),
            Pin(num='6',name='IOB6',func=pin_types.BIDIR),
            Pin(num='7',name='IOB5',func=pin_types.BIDIR),
            Pin(num='8',name='IOB4',func=pin_types.BIDIR),
            Pin(num='9',name='IOB3',func=pin_types.BIDIR),
            Pin(num='10',name='IOB2',func=pin_types.BIDIR),
            Pin(num='11',name='IOB1',func=pin_types.BIDIR),
            Pin(num='12',name='IOB0',func=pin_types.BIDIR),
            Pin(num='13',name='IOA7',func=pin_types.BIDIR),
            Pin(num='14',name='IOA6',func=pin_types.BIDIR),
            Pin(num='15',name='IOA5',func=pin_types.BIDIR),
            Pin(num='16',name='IOA4',func=pin_types.BIDIR),
            Pin(num='17',name='IOA3',func=pin_types.BIDIR),
            Pin(num='18',name='IOA2',func=pin_types.BIDIR),
            Pin(num='19',name='IOA1',func=pin_types.BIDIR),
            Pin(num='20',name='IOA0',func=pin_types.BIDIR),
            Pin(num='21',name='DA7',func=pin_types.BIDIR),
            Pin(num='22',name='CLK',func=pin_types.INPUT),
            Pin(num='23',name='RESET',func=pin_types.INPUT),
            Pin(num='24',name='A9',func=pin_types.INPUT),
            Pin(num='25',name='A8',func=pin_types.INPUT),
            Pin(num='26',name='TEST2',func=pin_types.NOCONNECT),
            Pin(num='27',name='BDIR',func=pin_types.INPUT),
            Pin(num='28',name='BC2',func=pin_types.INPUT),
            Pin(num='29',name='BC1',func=pin_types.INPUT),
            Pin(num='30',name='DA7',func=pin_types.BIDIR),
            Pin(num='31',name='DA6',func=pin_types.BIDIR),
            Pin(num='32',name='DA5',func=pin_types.BIDIR),
            Pin(num='33',name='DA4',func=pin_types.BIDIR),
            Pin(num='34',name='DA3',func=pin_types.BIDIR),
            Pin(num='35',name='DA2',func=pin_types.BIDIR),
            Pin(num='36',name='DA1',func=pin_types.BIDIR),
            Pin(num='37',name='DA0',func=pin_types.BIDIR),
            Pin(num='38',name='AoutC',func=pin_types.OUTPUT),
            Pin(num='39',name='TEST1',func=pin_types.NOCONNECT),
            Pin(num='40',name='VCC',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'Arduino_ProMicro', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Arduino_ProMicro'}), 'ref_prefix':'U', 'fplist':None, 'footprint':'Module:Arduino_Pro_Micro', 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='TX',func=pin_types.OUTPUT),
            Pin(num='2',name='RX',func=pin_types.INPUT),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='GND2',func=pin_types.PWRIN),
            Pin(num='5',name='D2',func=pin_types.BIDIR),
            Pin(num='6',name='D3',func=pin_types.BIDIR),
            Pin(num='7',name='D4',func=pin_types.BIDIR),
            Pin(num='8',name='D5',func=pin_types.BIDIR),
            Pin(num='9',name='D6',func=pin_types.BIDIR),
            Pin(num='10',name='D7',func=pin_types.BIDIR),
            Pin(num='11',name='D8',func=pin_types.BIDIR),
            Pin(num='12',name='D9',func=pin_types.BIDIR),
            Pin(num='13',name='D10',func=pin_types.BIDIR),
            Pin(num='14',name='D16',func=pin_types.BIDIR),
            Pin(num='15',name='D14',func=pin_types.BIDIR),
            Pin(num='16',name='D15',func=pin_types.BIDIR),
            Pin(num='17',name='A1',func=pin_types.BIDIR),
            Pin(num='18',name='A3',func=pin_types.BIDIR),
            Pin(num='19',name='VCC',func=pin_types.PWRIN),
            Pin(num='20',name='RAW',func=pin_types.PWRIN)] }),
        Part(**{ 'name':'TL072', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TL072'}), 'ref_prefix':'U', 'fplist':['', ''], 'footprint':'Package_DIP:DIP-8_W7.62mm', 'keywords':'dual opamp', 'description':'Dual Low-Noise JFET-Input Operational Amplifiers, DIP-8/SOIC-8', 'datasheet':'http://www.ti.com/lit/ds/symlink/tl071.pdf', 'pins':[
            Pin(num='3',name='+',func=pin_types.INPUT,unit=1),
            Pin(num='2',name='-',func=pin_types.INPUT,unit=1),
            Pin(num='1',name='~',func=pin_types.OUTPUT,unit=1),
            Pin(num='5',name='+',func=pin_types.INPUT,unit=2),
            Pin(num='6',name='-',func=pin_types.INPUT,unit=2),
            Pin(num='7',name='~',func=pin_types.OUTPUT,unit=2),
            Pin(num='8',name='V+',func=pin_types.PWRIN,unit=3),
            Pin(num='4',name='V-',func=pin_types.PWRIN,unit=3)], 'unit_defs':[{'label': 'uA', 'num': 1, 'pin_nums': ['1', '2', '3']},{'label': 'uB', 'num': 2, 'pin_nums': ['7', '6', '5']},{'label': 'uC', 'num': 3, 'pin_nums': ['4', '8']}] }),
        Part(**{ 'name':'AudioJack2', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AudioJack2'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'Connector_Audio:Jack_3.5mm_QingPu_WQP-PJ301BM_Vertical_CircularHoles', 'keywords':'audio jack receptacle mono phone headphone TS connector', 'description':'Audio Jack, 2 Poles (Mono / TS)', 'datasheet':'~', 'pins':[
            Pin(num='S',name='~',func=pin_types.PASSIVE,unit=1),
            Pin(num='T',name='~',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'D_Schottky', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'D_Schottky'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'Diode_THT:D_DO-35_SOD27_P7.62mm_Horizontal', 'keywords':'diode Schottky', 'description':'Schottky diode', 'datasheet':'~', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] })])